import mongoose from "mongoose";
import {
  listingLifecycleStatuses,
  ownerDeclarationVersion,
  verificationLevels,
  verificationStatuses,
  verifiedListingDisclaimer,
} from "../constants.js";

const documentSchema = new mongoose.Schema(
  {
    documentId: { type: String, required: true },
    category: { type: String, required: true, trim: true },
    type: { type: String, required: true, trim: true },
    storageRef: { type: String, required: true, trim: true },
    originalFilename: { type: String, required: true, trim: true },
    mimeType: { type: String, required: true, trim: true },
    size: { type: Number, required: true, min: 0 },
    uploadedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    verificationStatus: {
      type: String,
      enum: ["UPLOADED", "UNDER_REVIEW", "ACCEPTED", "REJECTED", "EXPIRED", "REPLACED"],
      default: "UPLOADED",
    },
    reviewer: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    reviewedAt: Date,
    rejectionReason: { type: String, default: "", trim: true },
    expiresAt: Date,
    version: { type: Number, default: 1 },
    checksum: { type: String, default: "", trim: true },
  },
  { timestamps: true, _id: false },
);

const checklistItemSchema = new mongoose.Schema(
  {
    itemId: { type: String, required: true, trim: true },
    category: { type: String, required: true, trim: true },
    propertyType: { type: String, default: "Any", trim: true },
    description: { type: String, required: true, trim: true },
    mandatory: { type: Boolean, default: true },
    applicableCondition: { type: String, default: "", trim: true },
    status: {
      type: String,
      enum: ["PENDING", "PASS", "FAIL", "NOT_APPLICABLE"],
      default: "PENDING",
    },
    reviewer: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    reviewedAt: Date,
    notes: { type: String, default: "", trim: true },
    evidenceDocumentId: { type: String, default: "", trim: true },
  },
  { _id: false },
);

const riskFlagSchema = new mongoose.Schema(
  {
    code: { type: String, required: true, trim: true },
    label: { type: String, required: true, trim: true },
    severity: { type: String, enum: ["LOW", "MEDIUM", "HIGH", "CRITICAL"], required: true },
    status: { type: String, enum: ["OPEN", "REVIEWED", "DISMISSED"], default: "OPEN" },
    notes: { type: String, default: "", trim: true },
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    reviewedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    reviewedAt: Date,
  },
  { timestamps: true, _id: true },
);

const duplicateCandidateSchema = new mongoose.Schema(
  {
    listingId: { type: String, required: true, trim: true },
    confidence: { type: Number, min: 0, max: 1, required: true },
    reason: { type: String, required: true, trim: true },
    decision: {
      type: String,
      enum: ["PENDING", "MERGED", "REJECTED", "ALLOWED", "SEPARATE_PROPERTY"],
      default: "PENDING",
    },
    reviewer: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    reviewedAt: Date,
  },
  { _id: false },
);

const propertySchema = new mongoose.Schema(
  {
    id: { type: String, required: true, unique: true, index: true },
    title: { type: String, required: true, trim: true },
    category: {
      type: String,
      enum: ["Shop", "Flat", "Plot", "House", "Farm House"],
      required: true,
    },
    intent: { type: String, enum: ["Sale", "Rent"], required: true },
    price: { type: Number, required: true, min: 0 },
    location: {
      city: { type: String, required: true, trim: true },
      locality: { type: String, default: "", trim: true },
    },
    specs: {
      area: { type: Number, required: true, min: 0 },
      bedrooms: Number,
      bathrooms: Number,
      furnishing: String,
    },
    propertyDetails: {
      fullAddress: { type: String, default: "", trim: true },
      landmark: { type: String, default: "", trim: true },
      areaUnit: { type: String, enum: ["sq.ft", "sq.m", "sq.yd", "acre", "bigha"], default: "sq.ft" },
      plotArea: { type: Number, min: 0 },
      carpetArea: { type: Number, min: 0 },
      builtUpArea: { type: Number, min: 0 },
      floor: { type: String, default: "", trim: true },
      totalFloors: { type: String, default: "", trim: true },
      balconies: { type: Number, min: 0 },
      parking: { type: String, default: "", trim: true },
      availability: { type: String, default: "", trim: true },
      facing: { type: String, default: "", trim: true },
      roadWidth: { type: String, default: "", trim: true },
      leaseType: { type: String, default: "", trim: true },
      priceNegotiable: { type: Boolean, default: false },
      gatedCommunity: { type: Boolean, default: false },
      gasPipeline: { type: Boolean, default: false },
      waterSupply: { type: String, default: "", trim: true },
      powerBackup: { type: String, default: "", trim: true },
      fans: { type: Number, min: 0 },
      lights: { type: Number, min: 0 },
      wardrobes: { type: Number, min: 0 },
      acs: { type: Number, min: 0 },
      beds: { type: Number, min: 0 },
      geysers: { type: Number, min: 0 },
      highlights: [{ type: String, trim: true }],
    },
    images: [{ type: mongoose.Schema.Types.Mixed }],
    amenities: [{ type: String }],
    featured: { type: Boolean, default: false },
    status: {
      type: String,
      enum: ["New", "Active", "Price Drop"],
      default: "Active",
    },
    description: { type: String, default: "" },
    listingSource: {
      type: String,
      enum: ["Admin", "User"],
      default: "Admin",
    },
    reviewStatus: {
      type: String,
      enum: ["Pending Review", "Approved", "Needs Changes"],
      default: "Approved",
    },
    submittedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    ownerName: { type: String, default: "", trim: true },
    ownerEmail: { type: String, default: "", trim: true },
    ownerPhone: { type: String, default: "", trim: true },
    ownerDetails: {
      ownerName: { type: String, default: "", trim: true },
      ownerPhone: { type: String, default: "", trim: true },
      ownerEmail: { type: String, default: "", trim: true },
      ownerRole: {
        type: String,
        enum: ["Owner", "Landlord", "Developer", "Authorized Partner", "Broker", ""],
        default: "",
      },
      organizationName: { type: String, default: "", trim: true },
      ownerAddress: { type: String, default: "", trim: true },
      authorityType: { type: String, default: "", trim: true },
      publicContactName: { type: String, default: "", trim: true },
      publicContactRole: { type: String, default: "", trim: true },
    },
    termsAcceptedAt: Date,
    transactionType: { type: String, enum: ["sale", "rent", "lease"], default: undefined },
    ownershipType: { type: String, default: "", trim: true },
    legalOwnerName: { type: String, default: "", trim: true },
    publicLocation: { type: String, default: "", trim: true },
    geo: {
      latitude: Number,
      longitude: Number,
    },
    financials: {
      rent: { type: Number, min: 0 },
      deposit: { type: Number, min: 0 },
      maintenance: { type: Number, min: 0 },
    },
    availabilityDate: Date,
    constructionStatus: { type: String, default: "", trim: true },
    propertyAge: { type: String, default: "", trim: true },
    rera: {
      providedNumber: { type: String, default: "", trim: true },
      state: { type: String, default: "", trim: true },
      status: {
        type: String,
        enum: ["NOT_APPLICABLE", "OWNER_PROVIDED", "CHECK_PENDING", "CHECKED", "MISMATCH", "ISSUE"],
        default: "NOT_APPLICABLE",
      },
      projectName: { type: String, default: "", trim: true },
      promoter: { type: String, default: "", trim: true },
      verifiedAt: Date,
      source: { type: String, default: "", trim: true },
      reviewer: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
      notes: { type: String, default: "", trim: true },
    },
    declarations: {
      loanOrEncumbrance: { type: String, default: "", trim: true },
      litigationOrDispute: { type: String, default: "", trim: true },
      ownerDeclarationAccepted: { type: Boolean, default: false },
      ownerDeclarationVersion: { type: String, default: ownerDeclarationVersion },
      acceptedAt: Date,
      acceptedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
      ipAddress: { type: String, default: "", trim: true },
      userAgent: { type: String, default: "", trim: true },
    },
    verification: {
      level: { type: String, enum: verificationLevels, default: "OWNER_LISTED" },
      status: { type: String, enum: verificationStatuses, default: "Pending Review", index: true },
      scope: { type: String, default: verifiedListingDisclaimer, trim: true },
      verifiedAt: Date,
      verifiedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
      expiresAt: Date,
      rejectionReason: { type: String, default: "", trim: true },
      suspensionReason: { type: String, default: "", trim: true },
      reviewNotes: { type: String, default: "", trim: true },
    },
    lifecycleStatus: {
      type: String,
      enum: listingLifecycleStatuses,
      default: "Active",
      index: true,
    },
    publishedAt: Date,
    archivedAt: Date,
    soldAt: Date,
    rentedAt: Date,
    leasedAt: Date,
    documents: [documentSchema],
    verificationChecklist: [checklistItemSchema],
    riskFlags: [riskFlagSchema],
    duplicateCandidates: [duplicateCandidateSchema],
  },
  { timestamps: true },
);

propertySchema.index({
  title: "text",
  "location.city": "text",
  "location.locality": "text",
  category: "text",
});

export const Property = mongoose.model("Property", propertySchema);
